const propertyInfoVal = (data) => {
    return {
        propertyAddress: data.propertyAddress,
        city: data.city,
        state: data.state,
        county: data.county,
        zip: data.zip,
        totalSqf: data.lotSqf,
        costPerSqf: data.costPerSqf,
        totalLivingSQF: data.totalLivingSQF,
        mainFloor: data.mainFloor,
        secondFloor: data.secondFloor,
        thirdFloor: data.thirdFloor,
        yearBuilt: data.yearBuilt,
        bed: data.bed,
        bath: data.bath,
        fullBath: data.fullBath,
        halfBath: data.halfBath,
        oneThirdBath: data.oneThirdBath,
        basement: data.basement,
        finishedBasement: data.finishedBasement,
        finishedAttic: data.finishedAttic,
        garages: data.garages,
        garageType: data.garageType,
        garageSqf: data.garageSqf,
        enclosedPorch: data.enclosedPorch,
        bonusRoom: data.bonusRoom,
        family: data.family,
        kitchen: data.kitchen,
        fireplace: data.fireplace,
        subdivision: data.subdivision,
        PropertyDescription: data.PropertyDescription,
        legalDesc: data.legalDesc,
        extWall: data.extWall,
        roofing: data.roofing,
        ac: data.ac,
        heating: data.heating,
        poolSpa: data.poolSpa,
        stories: data.stories,
        propertyType: data.propertyType,
        specificPropertyType: data.specificPropertyType,
        parcelId: data.parcelId,
        countyValue: data.countyValue,
        prcURL: data.prcURL,
        countyAssessorURL: data.countyAssessorURL,
        gisURL: data.gisURL,
        treasurerURL: data.treasurerURL,
        taxBillUrl: data.taxBillUrl,
        zillowURL: data.zillowURL,
        zestimate: data.zestimate,
        redfinUrl: data.redfinUrl,
        redfinEst: data.redfinEst,
        realtorURL: data.realtorURL,
        realtorEst: data.realtorEst,
        truliaURL: data.truliaURL,
        truliaEst: data.truliaEst,
        harUrl: data.harUrl,
        harEst: data.harEst,
        beenVerifiedURL: data.beenVerifiedURL,


        ename: data.elementarySchool && data.elementarySchool.ename,
        eranking: data.elementarySchool && data.elementarySchool.eranking,
        edistance: data.elementarySchool && data.elementarySchool.edistance,

        mname: data.middleSchool && data.middleSchool.mname,
        mranking: data.middleSchool && data.middleSchool.mranking,
        mdistance: data.middleSchool && data.middleSchool.mdistance,
        
        hname: data.highSchool && data.highSchool.hname,
        hranking: data.highSchool && data.highSchool.hranking,
        hdistance: data.highSchool && data.highSchool.hdistance
    }

}

export default propertyInfoVal;